automatic: False # Autonoumous hitting

fixed_flux: True # Wether to use a fixed flux for each hit (otherwise uses file below in a loop)
desired_fluxes_filename: "exp_test.txt" # This file MUSt be in 'desired_hitting_fluxes' folder

safety_distance: 1.3 # distance at which to PAUSE the robots when running autonomously

iiwa7:

  ref_velocity:
    x: 0.3
    y: 0.0
    z: 0.0

  ref_orientation:
    w: 0.707
    x: -0.707
    y: 0
    z: 0

  hit_direction:
    x: 0
    y: 1 
    z: 0

  hitting_flux : 1.2

  return_position:
    x: 0.55
    y: -0.3
    z: 0.3 #.25

  object_offset:
    x : 0.02
    y : -0.15
    z : -0.05


iiwa14:

  ref_velocity:
    x: 0.3
    y: 0.0
    z: 0.0

  ref_orientation: #[0.734, 0.012, 0.028, 0.0678]
    w: -0.707
    x: -0.707
    y: 0
    z: 0

  hit_direction:
    x: 0
    y: -1 
    z: 0

  hitting_flux : 1.2
    
  return_position:
    x: 0.55 #.6 
    y: 0.3  
    z: 0.3 #.20
    
  object_offset:
    x : 0.05
    y : 0.15
    z : -0.05

